AllCops:
  Exclude:
    - Gemfile
    - spec/**/*
    - script/*
    - cookbooks/**/*
    - bin/*
  TargetRubyVersion: 2.5.3
  TargetRailsVersion: 6.0.3.1

Metrics/ClassLength:
  Enabled: true
  CountComments: false
  Max: 100

Metrics/LineLength:
  Max: 120
  # To make it possible to copy or click on URIs in the code, we allow lines
  # containing a URI to be longer than Max.
  AllowHeredoc: true
  AllowURI: true
  URISchemes:
    - http
    - https

Metrics/MethodLength:
  Enabled: Yes
  Max: 15
  CountComments: false

Metrics/ParameterLists:
  Max: 5

Metrics/ModuleLength:
  Enabled: Yes
  Max: 100
  CountComments: false

Rails:
  Enabled: true

Rails/Output:
  Enabled: true

Rails/SaveBang:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/DocumentationMethod:
  Enabled: false

Layout:
  EnforcedStyle: leading

Naming:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: false
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false
