AllCops:
  Exclude:
    - Gemfile
    - spec/**/*
    - script/*
    - cookbooks/**/*
    - bin/*
    - db/**/*
    - config/**/*
  TargetRubyVersion: 3.5
  NewCops: enable
  SuggestExtensions: false
  DisabledByDefault: false

plugins:
  - rubocop-rails

Metrics/ClassLength:
  Enabled: true
  CountComments: false
  Max: 100

Layout/LineLength:
  Max: 120
  # To make it possible to copy or click on URIs in the code, we allow lines
  # containing a URI to be longer than Max.
  AllowHeredoc: true
  AllowURI: true
  URISchemes:
    - http
    - https

Style/Documentation:
  Enabled: false

# Disable I18n cop for now - we can enable later when adding proper i18n
Rails/I18nLocaleTexts:
  Enabled: false

# Allow some flexibility in method complexity for controllers
Metrics/AbcSize:
  Max: 25

Metrics/MethodLength:
  Max: 15

# Allow action filters for inherited actions
Rails/LexicallyScopedActionFilter:
  Enabled: false

# Allow html_safe for helper methods (with caution)
Rails/OutputSafety:
  Enabled: false
#
#Metrics/ParameterLists:
#  Max: 5
#
#Metrics/ModuleLength:
#  Enabled: Yes
#  Max: 100
#  CountComments: false
#
#Rails:
#  Enabled: true
#
#Rails/Output:
#  Enabled: true
#
#Rails/SaveBang:
#  Enabled: true
#
#Style/Documentation:
#  Enabled: false
#
#Style/DocumentationMethod:
#  Enabled: false
#
#Layout:
#  EnforcedStyle: leading
#
#Naming:
#  Enabled: true
#
#Style/FrozenStringLiteralComment:
#  Enabled: false
#
#Style/StringLiterals:
#  Enabled: false
#  EnforcedStyle: double_quotes
