name: CI Pipeline
on: 
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: alpha_blog_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    env:
      RAILS_ENV: test
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/alpha_blog_test
      NODE_ENV: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.4
          bundler-cache: true

      - name: Handle yanked gems
        run: |
          # If bundle install fails due to yanked gems, try to update them
          if ! bundle check; then
            echo "Bundle check failed, attempting to resolve yanked gems..."
            bundle update rubyzip nokogiri rack thor uri net-imap || true
            bundle install
          fi

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'yarn'

      - name: Install JavaScript dependencies
        run: yarn install --frozen-lockfile

      - name: Setup database
        run: |
          bundle exec rails db:create
          bundle exec rails db:schema:load

      - name: Precompile assets
        run: bundle exec rails assets:precompile

      - name: Run RuboCop
        run: bundle exec rubocop

      - name: Run RSpec tests
        run: bundle exec rspec

      - name: Run system tests
        run: bundle exec rails test:system

  security:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.4
          bundler-cache: true

      - name: Run Brakeman security scan
        run: bundle exec brakeman --exit-on-warn

      - name: Run bundle audit
        run: |
          bundle exec bundle audit --update
          bundle exec bundle audit

  deploy:
    needs: [test, security]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to production
        run: echo "Add your deployment steps here"
        # Example for Heroku:
        # - name: Deploy to Heroku
        #   uses: akhileshns/heroku-deploy@v3.12.12
        #   with:
        #     heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        #     heroku_app_name: "your-app-name"
        #     heroku_email: "your-email@example.com"